### ISSUE TITLE
Failing playback on Firefox Nightly native Web MIDI support

### ISSUE THREAD

**Issue by infojunkie** [mmontag/dx7-synth-js#12]
There's ongoing work to add [native Web MIDI support to Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=836897).

To validate the implementation, we're wiring a Web MIDI producer to your synth and expecting it to work correctly, as it does on Chrome. However, it's not working correctly at the moment, [as per this ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1750763).

Your review would be appreciated!

**Comment by mmontag** [comment]
Thanks for reporting, I'll look into this shortly. Will be great to get Web MIDI in Firefox.

**Comment by mmontag** [comment]
@infojunkie could you provide more detail/steps to reproduce?  Anything in the JS console?

I don't think I'm doing anything too strange with Web MIDI... midi.js is based on some example code from Chris Wilson, if I recall correctly.

**Comment by infojunkie** [comment]
The steps to reproduce are [detailed in the ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1750763#c0).

The JS console log on your side shows this suspicious warning:
`unreachable code after return statement midi.js:16` [[Learn More]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return)

**Comment by infojunkie** [comment]
[Further testing](https://bugzilla.mozilla.org/show_bug.cgi?id=1750763#c4) revealed that a slightly modified setup where the Web MIDI producer runs on Chrome (and your synth still runs on FF) does not exhibit this bug. I think this is strong evidence that the problem is elsewhere. Closing this issue.

**Comment by mmontag** [comment]
Okay, thanks for the heads up and happy hunting 🙂
