### ISSUE TITLE
MIDI input and playback broken in Chrome 56

### ISSUE THREAD

**Issue by mkfmnn** [mmontag/dx7-synth-js#3]
After updating to Chrome 56, I'm still able to use the computer keyboard to trigger notes, and the demo buttons work as expected, but MIDI input seems to be ignored and nothing happens after selecting a MIDI file from the drop-down and pressing "play".

When using Chromium 55.0.2883.95 (which works), this message appears in the console, which may or may not be related:

>MIDIMessageEvent.receivedTime is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5665772797952000 for more details.

**Comment by mmontag** [comment]
Thanks for the report! I can reproduce the problem, investigating now.

**Comment by mmontag** [comment]
Fixed in a804a84
